name: getx_todo_list
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
